set -g history-limit 25000

set -g mouse on
 
set-window-option -g mode-keys vi

set -g focus-events on
 
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"
 
setw -g aggressive-resize on

set -g @plugin "tmux-plugins/tpm"

set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin "tmux-plugins/tmux-logging"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "catppuccin/tmux"

# tmux-continuum
set -g @continuum-restore "on"

# tmux-logging
set -g @logging-path "~/logdump"
set -g @screen-capture-path "~/screencapture"
set -g @save-complete-history-path "~/historydump"

# tmux-catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# tpm-initialize
run "~/.tmux/plugins/tpm/tpm"
